spring:
  application:
    name: eureka-producer
    cloud:
      config:
        profile: dev
        label: master
        discovery:
          enabled: true
          serviceId: config-server
server:
  port: ${PRODUCER_PORT:2222}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ADDR:localhost}:${EUREKA_PORT:1111}/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30 #续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
