server:
  port: 5555

spring:
  application:
    name: config-server
  # git管理配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VitZhou/spring-cloud-demo
          searchPaths: config/config-repo
          username: vitzhou@gmail.com
          password: pwd
