spring:
  application:
    name: eureka-consumer
server:
  port: ${CONSUMER_PORT:3333}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ADDR:localhost}:${EUREKA_PORT:1111}/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30 #续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
