spring:
  application:
    name: api-gateway

server:
  port: ${GATEWAY_PORT:1101}

zuul:
  routes:
    test:
      strip-prefix: true
      path: /test/**
      serviceId: eureka-consumer
  add-proxy-headers: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ADDR:localhost}:${EUREKA_PORT:1111}/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30 #续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
