spring:
  application:
    name: api-gateway

server:
  port: 1101
zuul:
  routes:
    test:
      path: /test/**
      serviceId: feign-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
